window.translations = {
  'Gallery_Empty_Title': 'Add Your Images,',
  'Gallery_Empty_Title2': 'Video and Text',
  'Gallery_Empty_Description': 'Start adding now so people can see your work in the highest quality',
  'Gallery_Empty_Description2': 'Click Manage Media to get started',
  'Gallery_Sharing_Disabled_In_Editor': 'You’re in preview mode. You need to head to your published site to share photos.',
  'Gallery_Item_DefaultTitle_Short_Label': 'Add a catchy title',
  'Gallery_Item_DefaultTitle_Long_Label': 'Give your item a catchy title',
  'Gallery_Item_DefaultDescription_Short_Label': 'Tell your visitors a little about your item.',
  'Gallery_Item_DefaultDescription_Long_Label': 'Add a description to your item so your visitors can know the story behind your image or video. Tell them about where it was taken, what kind of equipment you used and the story that lead up to the moment.',
  'Gallery_Item_DefaultLink_Label': 'Check out Wix.com',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header': 'Time To Create',
  'Gallery_ArtStore_Organize_Images_EmptyState_Text': 'Start by adding your high quality images',
  'Gallery_ArtStore_Organize_Images_EmptyState_Get_Started': 'Get Started',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header2': 'Your Stunning Art Store',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Main_Label': 'Main',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Design_Label': 'Design',
  'Gallery_ArtStore_Cart_Settings_Design_Select_Layout_Label': 'Select Layout',
  'Gallery_ArtStore_Cart_Settings_Design_Icon_Color_Label': 'Icon Color',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Label': 'Font Style & Color',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Text_Label': 'Button Text',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Default_Text': 'Add to Cart',
  'Gallery_ArtStore_Cart_Settings_Main_Text': 'Customize your cart icon with a different style and color',
  'Gallery_ArtStore_Cart_Settings_Main_Button': 'Customize Icon',
  'Gallery_ArtStore_UOU_Add_To_Cart_Button': 'Add to Cart',
  'Gallery_ArtStore_UOU_Select_License_Label': '',
  'Gallery_User_Set_Payment_Screen_Header': 'Set Up Your Payment Method to Start Selling',
  'Gallery_User_Set_Payment_Screen_Text': 'Visitors cannot make a purchase because you haven’t set up your payment method yet. To set up your payment method, go to the Store tab and click ‘Get Paid.’',
  'Gallery_User_Set_Payment_Screen_Ok_Button': 'OK',
  'Gallery_UOU_No_Online_Payment_Screen_Text': 'Checkout for selected items is unavailable at this time. Please contact us, to complete your purchase.',
  'Gallery_UOU_No_Online_Payment_Screen_Ok_Button': 'OK',
  'Gallery_ArtStore_UOU_Continue_Checkout_Label': 'Continue to Checkout',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Title': '',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Text': '',
  'Gallery_ArtStore_ExpandMode_User_Message_Upload_Images': 'You can only sell your images. To upload your own, go to ‘Manage Media.’',
  'Gallery_Read_More': 'Read More',
  'Gallery_Read_Less': 'Read Less',
  'Gallery_Fullscreen_Mobile_Share': 'Share',
  'Gallery_ArtStore_User_ProviderDown_Message': 'Sorry, there\'s a technical issue and Wix Art Store couldn\'t be loaded. Click refresh or try again later.',
  'Gallery_ArtStore_UoU_ProviderDown_Message': 'Sorry, but we\'re experiencing a technical issue. Try refreshing the page or check back later.',
  'Gallery_Hover_Download_FreeImages_Text': 'Your visitors will be able to download your original images (but not any free Wix images).',
  'Gallery_OnStage_UoU_Welcome_Text': 'Welcome to My Art Store. Click an Image to Buy It.',
  'Gallery_OnStage_UoU_BuyNow_Label': 'Buy Now',
  'Gallery_OnStage_UoU_ImageTitle_Label': 'Image Title',
  'Gallery_ArtStore_UOU_TermsOfUse_Label': 'Terms of Use',
  'Gallery _CartView_Cart_Label': 'Cart'
}